Revisión
RosanaPeralta/TPO_P2_VN_grupo_03 pull request #1
Opened 2024-05-22 11:07 UTC by RosanaPeralta

Hola profe,
Espero se encuentre bien.

Abro este PR con el fin de chequear el enfoque que estamos adoptando para el trabajo práctico junto con el equipo.

Saludos!

2024-05-23 17:29 UTC, nmonzonc3t requested changes

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +                row.remove();
Este remove se hace sobre row, que también es aux2.getFirst() ya que lo que devuelve siempre es una referencia a memoria. Como no se está reconstruyendo, acá se están perdiendo los valores. Pueden por ejemplo, en la línea 38, copiar aux2.getFirst() en lugar de pasar su referencia

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +            for(int j = 0; j < countColumns-1-i; j++){
Acá sería <=

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +        if(queueOfStacks.isEmpty()){
Si mueven este condicional, al inicio del método, se evitan que se ejecute el copy en ocasiones donde no se necesita

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +                stackSize++;
stackSize está siendo reiniciado a 0 luego de cada iteración, excepto en la última. Pueden aprovechar esto para encontrar una inconsistencia, como por ejemplo, stacks de diferente altura. Deberian guardar la altura previa calculada y comparar que la altura obtenida en la iteración actual, coincida. La primera vez debería omitirse porque no hay algo previo.

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +        }
Esto de acá no está invirtiendo horizontalmente la queue que es lo que faltaría para completar el proceso ya que lo de arriba lo invierte verticalmente

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_2/model/stack/GenericDynamicSet.java
> +    public Object choose() {
Tiene que devolver E en lugar de Object

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_2/model/stack/GenericDynamicSet.java
> +    public void add(Object item) {
Deberían recibir un E, y se evitan el casteo de abajo

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_2/model/stack/GenericDynamicSet.java
> +            if(current.getValue() == item) {
Los valores se comparan con el método equals del objeto, ya que sino estas buscando siempre por referencia a memoria, cuando podrían haber sobreescrito el método equals para comparar igualdades en base a algo que no sea una referencia

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_2/model/stack/GenericDynamicSet.java
> +    public void remove(Object item) {
Idem acá, debería ser un E lo que remueve

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_2/model/stack/GenericPriorityQueue.java
> +    public void add(E item, int priority) {
La prioridad debe ser un tipo genérico que herede de la interfaz Comparable. Se los dejo como tip para que lo investiguen

2024-05-23 17:29 UTC, nmonzonc3t commented on src/main/java/org/example/Ejercicio2_3/model/stack/QueueOfQueueUtil.java
> +                throw new RuntimeException("No se puede iterar sobre una cola vacia");
Este error no va, la concatenación de una cola vacía es lo mismo que no hacer nada. Es decir, bajo la operación de concatenar, la cola vacía es el elemento neutro. Así que acá debería reemplazarse el "throw new..." por un "continue", ya que concatenar algo vacío es como no hacer nada.

2024-06-17 16:55 UTC, DiSavoia101 commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +            Stack row = aux2.getFirst();
Buenas profe, ciertamente resulta en una mala selección a la hora de nombrar la variable por nuestra parte, pues lo que representa la variable "row" es en realidad un paso en el código donde contamos la cantidad de elementos de esta columna para así saber cuantas filas habrá. ¿Considera menester el cambiar los nombres a estas variables para mejorar su claridad? ¿o con dejar una aclaración en el código bastará?

2024-06-17 20:37 UTC, nicolas-monzon commented on src/main/java/org/example/Ejercicio2_1/model/stack/QueueOfStacksUtil.java
> +            Stack row = aux2.getFirst();
Hola! Si, si bien no afecta a la lógica, la claridad es importante

2024-06-17 21:42 UTC, closed without merging